elasticsearch:
  client:
    podLabels:
      branch: $BRANCH_NAME
      resource: pod
      team: platform
      usage: utests
    tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
    nodeSelector:
      team: platform
  master:
    podLabels:
      branch: $BRANCH_NAME
      resource: pod
      team: platform
      usage: utests
    tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
    nodeSelector:
      team: platform
  data:
    podLabels:
      branch: $BRANCH_NAME
      resource: pod
      team: platform
      usage: utests
    tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
    nodeSelector:
      team: platform
tags:
  elasticsearch: true
